force-app/main/default/objects/Solitair_Metadata__c/Solitair_Metadata__c.object-meta.xml
<CustomObject>
    <label>Solitair Metadata</label>
    <nameField>
        <label>Solitair Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solitair Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solitair_Metadata__c/fields/Solitair_Game_Id__c.field-meta.xml
<CustomField>
    <fullName>Solitair_Game_Id__c</fullName>
    <label>Solitair Game Id</label>
    <referenceTo>Solitair_Game__c</referenceTo>
    <relationshipLabel>Solitair Metadata</relationshipLabel>
    <relationshipName>Solitair_Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solitair_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solitair_Metadata__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Model/Board.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-24-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global with sharing class Board {
    public Board() {
    }

    public Board cloneBoard() {
        String jsonStr = JSON.serialize(this);
        Board newBoard = (Board) JSON.deserialize(jsonStr, Board.class);
        newBoard.boardId = null;
        newBoard.gameId = this.gameId;
        newBoard.parentId = this.boardId;
        newBoard.key = this.key;
        newBoard.level = this.level + 1;
        return newBoard;
    }

    global Solitair_Metadata__c mapperBoardToBoardDb(Id gameId, String boardType, String jsonString, String key) {
        Solitair_Metadata__c boardDb = new Solitair_Metadata__c();
        boardDb.Solitair_Game_Id__c = gameId;
        boardDb.Type__c = boardType;
        boardDb.Value__c = jsonString;
        boardDb.Key__c = key;
        return boardDb;
    }

    global Id boardId;
    global Id parentId;
    global Id gameId;
    global Integer level;
    global String lastMove;
    global List<Line> fundamental;
    global List<Line> stockPail;
    global List<Line> runningTrack;
    global String key;
}